version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  fastapi:
    build:
      context: .
      dockerfile: /Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongodb

  celery_worker:
    build:
      context: .
      dockerfile: /Dockerfile.celery
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongodb_data: